# Generated by Django 5.1.6 on 2025-02-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_organisation_alter_lead_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('new', ' New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('unconverted', 'Unconverted')], default=('new', ' New'), max_length=50)),
            ],
        ),
    ]
