# Generated by Django 5.1.6 on 2025-02-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoty_leads', to='lead.category'),
            preserve_default=False,
        ),
    ]
