# Generated by Django 5.1.6 on 2025-02-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_category_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('converted', 'Converted'), ('unconverted', 'Unconverted')], default=('contacted', 'Contacted'), max_length=50),
        ),
    ]
