# Generated by Django 5.1.6 on 2025-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_alter_lead_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('converted', 'Converted'), ('unconverted', 'Unconverted')], default=('unconverted', 'Unconverted'), max_length=50),
        ),
    ]
