# Generated by Django 5.1.6 on 2025-02-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('converted', 'Converted'), ('unconverted', 'Unconverted')], default='unconverted', max_length=50),
        ),
    ]
