name: Publish Docker Image

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker Image
        run: 
          docker login ghcr.io --username amuhailo --password ${{ secrets.PAT }}
          docker build . -t ghcr.io/amuhailo/docker-image
          docker push ghcr.io/amuhailo/docker-image